name: social_network_utilities
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.12.30
  any_link_preview: ^3.0.1
  better_player: ^0.0.63
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  device_info_plus: ^9.0.3
  expandable: ^5.0.1
  firebase_dynamic_links: ^5.3.7
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.18.1
  line_icons: ^2.0.3
  localstorage: ^4.0.1+4
  omni_datetime_picker: ^1.0.9
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  reorderable_grid_view: ^2.2.7
  sticky_headers: ^0.3.0+2
  table_calendar: ^3.0.9
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
